### ISSUE TITLE
Run on multiple files

### ISSUE THREAD

**Issue by gentlegiantJGC** [dzhu/rstfmt#11]
Is there a way to easily specify multiple files with this tool?

I have found that you can specify space separated paths and it will run on all of them but this means you have to add all of the paths as arguments.

I believe linux has glob support in the command line so it will automatically expand the glob but windows does not.

A workaround is to write some code to call the tool for each file but this is slow.

The ideal solution is for the tool to either support glob strings and expand them or support directory inputs like Black does.

**Comment by gentlegiantJGC** [comment]
Feel free to use this as a starting point.
https://github.com/gentlegiantJGC/rstfmt/commit/6cdeb450748c3f9db9ecb4d99e448237efab1646

**Comment by dzhu** [comment]
Hello, and thanks for your suggestion! Sorry for the delay, but version 0.0.10, now available on PyPI, supports this. When passed a directory as an argument, it operates on all files in the directory with the right extension (`rst` by default, settable with the `--ext` option). Please let me know if the new behavior works for you!

**Comment by gentlegiantJGC** [comment]
Thanks. I am back to documenting again so this will come in handy again.
