### ISSUE TITLE
Inconsistent list formatting

### ISSUE THREAD

**Issue by kayhayen** [dzhu/rstfmt#13]
Hello,

it seems that if a list contains items which are broken to 3 lines, there is spaces in between them:

Below is an example. I would love to be able to enforce this, because it is rather random, and in my changelog, it looks inconsistent because I have these sections with list items, and some look cramped and others nice and with space.

I don't know if it's acceptable for you to make this configurable? So far only width is configurable, and I take that you may like black not want to go there. What's your take?

```
****************
 Organisational
****************

-  Enhanced Github issue raising instructions.
-  Apply ``rstfmt`` to all documentation and make it part of the commit
   hook.
-  Make sure to check Scons files as well. This would have caught the
   code used to disable ``clcache`` temporarily.
-  Do not mention Travis in PR template anymore, we have stopped using
   it.
-  Updated requirements to latest versions.
-  Bump requirements for development to 3.7 at least, toosl like black
   do not work with 3.6 anymore.
-  Started work on Nuitka Python, a CPython fork intended for enhanced
   performance and standalone support with Nuitka.

**********
 Cleanups
**********

-  Determine system prefix without virtualenv outside of Scons, such
   that plugins can share the code. There was duplication with the
   ``numpy`` plugin, and this will only be more complete using all
   approaches. This also removes a lot of noise from the scons file
   moving it to shared code.

-  The Qt plugins now collect QML files with cleaner code.
```

**Comment by dzhu** [comment]
Yeah, I think this is the formatting choice I'm most uncertain about, but [there *is* a reason for it](https://github.com/dzhu/rstfmt/commit/8676ef8d772b23d43981910385742153f7fb588f). If I *were* to change it, I would prefer to change the output for everybody rather than make it an option, for the reason you conjectured. At the moment, I'm still not planning to change it at all, but that is very much not set in stone and I will keep your feedback in mind!

**Comment by kayhayen** [comment]
I can live without it, I did a stupid bit of python code that scans the lists and injects new lines after list items if there is none, which makes it consistent. I totally accept your idea, and you save me a lot of time, so I can waste a tiny bit on addressing my sense for consistency there. I understand that most documents are not like the one of mine there. Closing therefore.
