### ISSUE TITLE
Support for ..raw: pass through is needed

### ISSUE THREAD

**Issue by kayhayen** [dzhu/rstfmt#2]
I am very excited, I found this tool, however I have a file where it crashes, on what seems to be incompleteness.

In my Nuitka (http://nuitka.net) User Manual I have this:

.. raw:: pdf

   PageBreak oneColumn
   SetPageCounter 1

This gives ``ValueError: Unknown node type raw!`` and that's fair. I guess, it's needed to pass through stuff that is backend specific, like here for rst2pdf only.

I can remove this code, and only insert it when I render with rst2pdf, but I would like to avoid that of course.

**Comment by kayhayen** [comment]
Not in 0.0.7 as on PyPI

**Comment by dzhu** [comment]
Thanks for your interest, and sorry for the delay! This should be fixed in version 0.0.8, which is now available on PyPI, so I'm closing the issue. Feel free to comment here or open a new issue if anything goes wrong.
