### ISSUE TITLE
pre-commit hook metadata was added but never released

### ISSUE THREAD

**Issue by dannysauer** [dzhu/rstfmt#22]
Using this repository as a sourc for a pre-commit hook currently requires using the "master" tag, because there is no tag which includes the `.pre-commit-hooks.yaml` file.  That's a problem, because, as pre-commit puts it:

> [WARNING] The 'rev' field of repo 'https://github.com/dzhu/rstfmt' appears to be a mutable reference (moving tag / branch).  Mutable references are never updated after first install and are not supported.  See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details.  Hint: `pre-commit autoupdate` often fixes this.

So, it'd be handy if there could be a v0.0.12 bump. :)

**Comment by dannysauer** [comment]
Also, thanks for adding the file to begin with.  I forked specifically to do that before I realized the file was already in place. :D

**Comment by dzhu** [comment]
Done!
