### ISSUE TITLE
Add sdist to PyPI

### ISSUE THREAD

**Issue by jayvdb** [dzhu/rstfmt#23]
https://pypi.org/project/rstfmt/#files only has a wheel.

it would be very helpful for distro packagers if a "sdist" tarball was added, especially if the tests are included in the sdist.

**Comment by dzhu** [comment]
I haven't dealt with producing sdist files before; does this look right? [rstfmt-0.0.12.tar.gz](https://github.com/dzhu/rstfmt/files/11118572/rstfmt-0.0.12.tar.gz)

(If so, I'll start putting them on PyPI; just attaching here first for a sanity check.)

**Comment by jayvdb** [comment]
LGTM @dzhu

**Comment by dzhu** [comment]
Okay,
 I've uploaded a tarball for the new 0.0.13 release, and will continue to do so going forward.
