### ISSUE TITLE
Unknown directive type 'currentmodule'

### ISSUE THREAD

**Issue by matthewhegarty** [dzhu/rstfmt#26]
Looks like an interesting project but I get the attached error when running on django-import-export

```
rstfmt --ext rst docs
```

- v0.0.12
- python3.10

https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#directive-py-currentmodule

[st1.txt](https://github.com/dzhu/rstfmt/files/10687665/st1.txt)

[versions.txt](https://github.com/dzhu/rstfmt/files/10687691/versions.txt)

**Comment by dzhu** [comment]
Thanks for the report! This should be [fixed](https://github.com/dzhu/rstfmt/commit/e0606b837f5cd6aa80e19af4e220a48fe7756203) in the new 0.0.13 release.
