### ISSUE TITLE
rstfmt updates timestamps of unchanged files

### ISSUE THREAD

**Issue by zyzzyxdonta** [dzhu/rstfmt#28]
Build systems like make and many other tools, including sphinx, use file timestamps to determine if sources were changed and targets need to be rebuilt. Currently, rstfmt updates the timestamps of files that were not changed, thus causing a full rebuild in a subsequent run of the build tool. It would be great to change this behaviour so that only real file changes cause an update to the timestamp.

**Comment by dzhu** [comment]
Thanks for the report! This should be [fixed](https://github.com/dzhu/rstfmt/commit/7fcdd22c173c7ce4d41016e9388407c244d1bc13) in the new 0.0.13 release.

**Comment by zyzzyxdonta** [comment]
Works great. Thank you so much!
